#!/bin/bash
# CC Executor Deployment Script
# Generated by self-improving prompt

set -e

echo "CC Executor Docker Deployment"
echo "============================"

# Check Docker and Docker Compose
if ! command -v docker &> /dev/null; then
    echo "Error: Docker is not installed"
    exit 1
fi

if ! docker compose version &> /dev/null; then
    echo "Error: Docker Compose is not installed"
    exit 1
fi

# Create necessary directories
echo "Creating directories..."
mkdir -p logs data claude-config
chmod 755 logs data claude-config

# Check if .env exists
if [ ! -f .env ]; then
    echo "Creating .env file..."
    touch .env
fi

# Build and start services
echo "Building Docker images..."
docker compose build --no-cache

echo "Starting services..."
docker compose up -d

# Wait for services to be healthy
echo "Waiting for services to be healthy..."
sleep 10

# Check service status
docker compose ps

# Show authentication instructions
echo ""
echo "Services are running!"
echo ""
echo "To authenticate Claude Code:"
echo "  1. Run: curl -X POST http://localhost:8001/auth/claude"
echo "  2. Follow the authentication URL provided"
echo ""
echo "To test the API:"
echo "  curl http://localhost:8001/health"
echo ""
echo "To view logs:"
echo "  docker compose logs -f"
